---
- name: Dependency Packages
  yum: name={{ item }} state=latest update_cache=true
  with_items:
    - gcc
    - gcc-c++
    - glibc-headers
    - openssl-devel
    - readline
    - libyaml-devel
    - readline-devel
    - zlib
    - zlib-devel
