---
- name: NTPのインストール
  yum:
    name: ntp
    state: latest

- name: NTPの設定ファイルの設置
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntpd

# - name: NTPの起動
#   service:
#     name: ntp
#     state: started
#     enabled: yes
